---
title: "03_houtsaegerduinen"
output: html_document
---

De Houtsaegerduinen (90 ha, beheerd door ANB) zijn grotendeels gefixeerd en sterk verstruweeld. Sedert 1997 graast er jaarrond een kudde ezels (Cotentin Flamande) binnen een blok van 74 ha. Aanvankelijk werden 6 ezels geïntroduceerd. In 2020 graasden er 10 dieren en in de periode 2021 - 2023 groeide dit aan tot 25 dieren. Deze kudde geraakte jaarlijks gesplitst en omdat we de kudde maar met één tracker volgen, is het beeld dat we schetsen van het terreingebruik mogelijks onvolledig. Aanvankelijke doelstelling was het open maken van het struweel en uitbreiden van de verspreide duingraslandfragmenten. De ezelbegrazing blijkt daartoe onvoldoende. In 2018 werden daarom twee blokken met een gezamenlijke oppervlakte van 4,4 ha volledig machinaal ontstruweeld. Het nabeheer gebeurt door intensieve schapen- en geitenbegrazing binnen verplaatsbare flexi-netten. In 2024 betrof het 186 dieren: 23 geiten en 150 schapen. Aanvullend grazen deze dieren ook geherderd in andere zones van het gebied. De geherderde kudde tracken we niet, waardoor we de totale graasdruk niet kunnen inschatten.