# Load functions
library(knitr)
library(dplyr)
library(targets)

source(file.path("scripts", "autoqmd_generate_children.R"))
source(file.path("scripts", "autoqmd_insert_includes.R"))

# Helper functions
firstup <- function(name) {
  paste0(
    toupper(substr(name, 1, 1)),
    tolower(substr(name, 2, nchar(name)))
  )
}

# Wrapper for child documents
autoqmd_prepare <- function(
  ...,
  template,
  child_dir,
  freeze = NULL,
  qmd_file,
  start_marker = "<!-- AUTOGENERATED-START -->",
  end_marker   = "<!-- AUTOGENERATED-END -->",
  page_break   = NULL,
  quiet = FALSE
) {
  child_files <- autoqmd_generate_children( # nolint: object_usage_linter
    ...,
    template = template,
    child_dir = child_dir,
    freeze = freeze
  )

  autoqmd_insert_includes( # nolint: object_usage_linter
    qmd_file = qmd_file,
    child_files = child_files,
    start_marker = start_marker,
    end_marker = end_marker,
    page_break = page_break,
    template = template,
    quiet = quiet
  )
}

# Globals
region_vec <- sort(
  c(
    "Boelaremeersen",
    "Bos t Ename",
    "Demerbroeken",
    "Hochter Bampd",
    "Hoge Kempen",
    "Houtsaegerduinen",
    "Kalmthoutse Heide",
    "Maldegemveld",
    "Moenebroek",
    "Negenoord Kerkeweerd",
    "Westhoek",
    "Ziepbeekvallei",
    "Zwinduinen",
    "Zwinschorren"
  )
)

repo_dir <- rprojroot::find_root_file(criterion = rprojroot::is_git_root)
# store <- file.path(repo_dir, "source", "targets", "data_preparation",
#                    "_targets")
# taxa_df <- tar_read("manual_taxon_mapping", store = store)

# -------------------------------
# Prepare child documents and add to qmd
# -------------------------------

# Species densities
autoqmd_prepare(
  species = region_vec,
  specname_cap = firstup(region_vec),
  specname_low = tolower(region_vec),
  label = gsub("\\s", ".", tolower(region_vec)),
  template = "_template_regio.qmd",
  child_dir = "child_files/gebieden",
  qmd_file = "2_resultaten.qmd",
  page_break = "clearpage",
  quiet = FALSE
)

# # Appendix detection curves (not frozen)
# autoqmd_prepare(
#   species = region_vec,
#   specname_cap = firstup(region_vec),
#   specname_low = tolower(region_vec),
#   label = gsub("\\s", ".", tolower(region_vec)),
#   template = "_species_detectioncurves.qmd",
#   child_dir = "child_files/spec_files_detection_curves",
#   qmd_file = "detection_curves.qmd",
#   quiet = FALSE
# )
#
# # Appendix density tables (not frozen)
# autoqmd_prepare(
#   species = region_vec,
#   specname_cap = firstup(region_vec),
#   specname_low = tolower(region_vec),
#   label = gsub("\\s", ".", tolower(region_vec)),
#   template = "_densities_tables.qmd",
#   child_dir = "child_files/spec_files_densities_tables",
#   qmd_file = "densities_tables.qmd",
#   page_break = "newpage",
#   quiet = FALSE
# )
